USE [master]
GO
/****** Object:  Database [HotelChain]    Script Date: 4/1/2025 11:19:06 PM ******/
CREATE DATABASE [HotelChain]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HotelChain', FILENAME = N'D:\SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\HotelChain.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HotelChain_log', FILENAME = N'D:\SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\HotelChain_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [HotelChain] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HotelChain].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [HotelChain] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [HotelChain] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [HotelChain] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [HotelChain] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [HotelChain] SET ARITHABORT OFF 
GO
ALTER DATABASE [HotelChain] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [HotelChain] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [HotelChain] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [HotelChain] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [HotelChain] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [HotelChain] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [HotelChain] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [HotelChain] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [HotelChain] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [HotelChain] SET  DISABLE_BROKER 
GO
ALTER DATABASE [HotelChain] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [HotelChain] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [HotelChain] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [HotelChain] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [HotelChain] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [HotelChain] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [HotelChain] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [HotelChain] SET RECOVERY FULL 
GO
ALTER DATABASE [HotelChain] SET  MULTI_USER 
GO
ALTER DATABASE [HotelChain] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [HotelChain] SET DB_CHAINING OFF 
GO
ALTER DATABASE [HotelChain] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [HotelChain] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [HotelChain] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [HotelChain] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'HotelChain', N'ON'
GO
ALTER DATABASE [HotelChain] SET QUERY_STORE = ON
GO
ALTER DATABASE [HotelChain] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [HotelChain]
GO
/****** Object:  Table [dbo].[Room]    Script Date: 4/1/2025 11:19:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Room](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[HotelId] [int] NOT NULL,
	[Price] [decimal](10, 2) NOT NULL,
	[Capacity] [nvarchar](50) NOT NULL,
	[SeaView] [bit] NOT NULL,
	[MountainView] [bit] NOT NULL,
	[Extendable] [bit] NOT NULL,
	[Amenities] [nvarchar](max) NULL,
	[ProblemsDamages] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Renting]    Script Date: 4/1/2025 11:19:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Renting](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CustomerId] [int] NULL,
	[RoomId] [int] NULL,
	[StartDate] [date] NOT NULL,
	[EndDate] [date] NOT NULL,
	[CheckInEmployeeId] [int] NOT NULL,
	[IsPaid] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[AvaliableRooms]    Script Date: 4/1/2025 11:19:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[AvaliableRooms] AS
SELECT Room.HotelID, Room.Id
FROM Room 
LEFT JOIN 
	Renting ON Room.id = Renting.RoomId
WHERE (Renting.id IS NULL);
GO
/****** Object:  Table [dbo].[Hotel]    Script Date: 4/1/2025 11:19:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Hotel](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[HotelChainId] [int] NOT NULL,
	[Star] [int] NULL,
	[NumRooms] [int] NOT NULL,
	[Address] [nvarchar](500) NOT NULL,
	[Email] [nvarchar](255) NOT NULL,
	[ManagerId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[Capcity]    Script Date: 4/1/2025 11:19:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[Capcity] AS
SELECT Hotel.ID, Room.Capacity
FROM Hotel
JOIN Room ON Hotel.Id = Room.HotelId;
GO
/****** Object:  Table [dbo].[Booking]    Script Date: 4/1/2025 11:19:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Booking](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CustomerId] [int] NOT NULL,
	[RoomId] [int] NOT NULL,
	[StartDate] [date] NOT NULL,
	[EndDate] [date] NOT NULL,
	[BookingDate] [date] NOT NULL,
	[IsConfirmed] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BookingArchive]    Script Date: 4/1/2025 11:19:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BookingArchive](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CustomerInfo] [nvarchar](max) NOT NULL,
	[RoomInfo] [nvarchar](max) NOT NULL,
	[StartDate] [date] NOT NULL,
	[EndDate] [date] NOT NULL,
	[BookingDate] [date] NOT NULL,
	[IsConfirmed] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Customer]    Script Date: 4/1/2025 11:19:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customer](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FullName] [nvarchar](255) NOT NULL,
	[Address] [nvarchar](500) NOT NULL,
	[IdType] [nvarchar](50) NOT NULL,
	[IdNumber] [nvarchar](100) NOT NULL,
	[RegistrationDate] [date] NOT NULL,
	[Password] [nvarchar](100) NULL,
	[Email] [nvarchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[IdNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Employee]    Script Date: 4/1/2025 11:19:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employee](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[HotelId] [int] NOT NULL,
	[FullName] [nvarchar](255) NOT NULL,
	[Address] [nvarchar](500) NOT NULL,
	[Ssn] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](100) NULL,
	[Email] [nvarchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Ssn] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EmployeeRole]    Script Date: 4/1/2025 11:19:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EmployeeRole](
	[EmployeeId] [int] NOT NULL,
	[RoleId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[EmployeeId] ASC,
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HotelChain]    Script Date: 4/1/2025 11:19:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HotelChain](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](255) NOT NULL,
	[NumHotels] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HotelChainAddress]    Script Date: 4/1/2025 11:19:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HotelChainAddress](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[HotelChainId] [int] NOT NULL,
	[Address] [nvarchar](500) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HotelChainContactEmail]    Script Date: 4/1/2025 11:19:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HotelChainContactEmail](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[HotelChainId] [int] NOT NULL,
	[Email] [nvarchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HotelChainContactPhone]    Script Date: 4/1/2025 11:19:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HotelChainContactPhone](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[HotelChainId] [int] NOT NULL,
	[PhoneNumber] [nvarchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HotelContactPhone]    Script Date: 4/1/2025 11:19:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HotelContactPhone](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[HotelId] [int] NOT NULL,
	[PhoneNumber] [nvarchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RentingArchive]    Script Date: 4/1/2025 11:19:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RentingArchive](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CustomerInfo] [nvarchar](max) NOT NULL,
	[RoomInfo] [nvarchar](max) NOT NULL,
	[StartDate] [date] NOT NULL,
	[EndDate] [date] NOT NULL,
	[CheckInEmployeeInfo] [nvarchar](max) NOT NULL,
	[IsPaid] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Role]    Script Date: 4/1/2025 11:19:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Role](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[RoleName] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [BookingIds]    Script Date: 4/1/2025 11:19:06 PM ******/
CREATE NONCLUSTERED INDEX [BookingIds] ON [dbo].[Booking]
(
	[RoomId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [HotelIds]    Script Date: 4/1/2025 11:19:06 PM ******/
CREATE NONCLUSTERED INDEX [HotelIds] ON [dbo].[Hotel]
(
	[Id] ASC,
	[HotelChainId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [HotelChainIds]    Script Date: 4/1/2025 11:19:06 PM ******/
CREATE NONCLUSTERED INDEX [HotelChainIds] ON [dbo].[HotelChain]
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Booking] ADD  DEFAULT (getdate()) FOR [BookingDate]
GO
ALTER TABLE [dbo].[Booking] ADD  DEFAULT ((1)) FOR [IsConfirmed]
GO
ALTER TABLE [dbo].[Customer] ADD  DEFAULT (getdate()) FOR [RegistrationDate]
GO
ALTER TABLE [dbo].[Renting] ADD  DEFAULT ((0)) FOR [IsPaid]
GO
ALTER TABLE [dbo].[Room] ADD  DEFAULT ((0)) FOR [SeaView]
GO
ALTER TABLE [dbo].[Room] ADD  DEFAULT ((0)) FOR [MountainView]
GO
ALTER TABLE [dbo].[Room] ADD  DEFAULT ((0)) FOR [Extendable]
GO
ALTER TABLE [dbo].[Booking]  WITH NOCHECK ADD FOREIGN KEY([CustomerId])
REFERENCES [dbo].[Customer] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Booking]  WITH NOCHECK ADD FOREIGN KEY([RoomId])
REFERENCES [dbo].[Room] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Employee]  WITH NOCHECK ADD FOREIGN KEY([HotelId])
REFERENCES [dbo].[Hotel] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[EmployeeRole]  WITH NOCHECK ADD FOREIGN KEY([EmployeeId])
REFERENCES [dbo].[Employee] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[EmployeeRole]  WITH NOCHECK ADD FOREIGN KEY([RoleId])
REFERENCES [dbo].[Role] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Hotel]  WITH NOCHECK ADD FOREIGN KEY([HotelChainId])
REFERENCES [dbo].[HotelChain] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Hotel]  WITH NOCHECK ADD  CONSTRAINT [FK_Hotel_Manager] FOREIGN KEY([ManagerId])
REFERENCES [dbo].[Employee] ([Id])
GO
ALTER TABLE [dbo].[Hotel] NOCHECK CONSTRAINT [FK_Hotel_Manager]
GO
ALTER TABLE [dbo].[HotelChainAddress]  WITH NOCHECK ADD FOREIGN KEY([HotelChainId])
REFERENCES [dbo].[HotelChain] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[HotelChainContactEmail]  WITH NOCHECK ADD FOREIGN KEY([HotelChainId])
REFERENCES [dbo].[HotelChain] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[HotelChainContactPhone]  WITH NOCHECK ADD FOREIGN KEY([HotelChainId])
REFERENCES [dbo].[HotelChain] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[HotelContactPhone]  WITH NOCHECK ADD FOREIGN KEY([HotelId])
REFERENCES [dbo].[Hotel] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Renting]  WITH NOCHECK ADD FOREIGN KEY([CheckInEmployeeId])
REFERENCES [dbo].[Employee] ([Id])
GO
ALTER TABLE [dbo].[Renting]  WITH NOCHECK ADD FOREIGN KEY([CustomerId])
REFERENCES [dbo].[Customer] ([Id])
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[Renting]  WITH NOCHECK ADD FOREIGN KEY([RoomId])
REFERENCES [dbo].[Room] ([Id])
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[Room]  WITH NOCHECK ADD FOREIGN KEY([HotelId])
REFERENCES [dbo].[Hotel] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Hotel]  WITH NOCHECK ADD CHECK  (([Star]>=(1) AND [Star]<=(5)))
GO
USE [master]
GO
ALTER DATABASE [HotelChain] SET  READ_WRITE 
GO
